version: "3"

services:
  yugabytedb-node1:
    image: yugabytedb/yugabyte:2.19.3.0-b140
    container_name: yugabytedb-node1
    networks:
      - custom-network
    ports:
      - "15433:15433"
      - "7001:7000"
      - "9001:9000"
      - "5433:5433"
    volumes:
      - ~/yugabyte_volume/node1:/home/yugabyte/yb_data
    restart: unless-stopped
    command: ["bin/yugabyted", "start", "--base_dir=/home/yugabyte/yb_data", "--daemon=false"]

  yugabytedb-node2:
    image: yugabytedb/yugabyte:2.19.3.0-b140
    container_name: yugabytedb-node2
    networks:
      - custom-network
    ports:
      - "15434:15433"
      - "7002:7000"
      - "9002:9000"
      - "5434:5433"
    volumes:
      - ~/yugabyte_volume/node2:/home/yugabyte/yb_data
    restart: unless-stopped
    command:
      ["bin/yugabyted", "start", "--join=yugabytedb-node1", "--base_dir=/home/yugabyte/yb_data", "--daemon=false"]

  yugabytedb-node3:
    image: yugabytedb/yugabyte:2.19.3.0-b140
    container_name: yugabytedb-node3
    networks:
      - custom-network
    ports:
      - "15435:15433"
      - "7003:7000"
      - "9003:9000"
      - "5435:5433"
    volumes:
      - ~/yugabyte_volume/node3:/home/yugabyte/yb_data
    restart: unless-stopped
    command:
      ["bin/yugabyted", "start", "--join=yugabytedb-node2", "--base_dir=/home/yugabyte/yb_data", "--daemon=false"]

networks:
  custom-network:
